apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofapp01-deploy
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: dofapp01
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dofapp01
    spec:
      containers:
      - name: app-cont
        image: kolevvm/dof:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dofapp01-svc
  labels:
    app: dofapp01
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: dofapp01
